// <auto-generated />
using GameTracker.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219143735_StudioSwitchIntToString")]
    partial class StudioSwitchIntToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("CategoryGame", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameCollectionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "GameCollectionID");

                    b.HasIndex("GameCollectionID");

                    b.ToTable("CategoryGame");
                });

            modelBuilder.Entity("GameStudio", b =>
                {
                    b.Property<int>("PublishedGamesID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudiosID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PublishedGamesID", "StudiosID");

                    b.HasIndex("StudiosID");

                    b.ToTable("GameStudio");
                });

            modelBuilder.Entity("GameTracker.Class.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("GameTracker.Class.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("games");
                });

            modelBuilder.Entity("GameTracker.Class.PlaySession", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HoursPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayedGameID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PlayedGameID");

                    b.HasIndex("UserId");

                    b.ToTable("playSessions");
                });

            modelBuilder.Entity("GameTracker.Class.Studio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("studios");
                });

            modelBuilder.Entity("GameTracker.Class.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("CategoryGame", b =>
                {
                    b.HasOne("GameTracker.Class.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameTracker.Class.Game", null)
                        .WithMany()
                        .HasForeignKey("GameCollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameStudio", b =>
                {
                    b.HasOne("GameTracker.Class.Game", null)
                        .WithMany()
                        .HasForeignKey("PublishedGamesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameTracker.Class.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudiosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameTracker.Class.PlaySession", b =>
                {
                    b.HasOne("GameTracker.Class.Game", "PlayedGame")
                        .WithMany("PlaySessions")
                        .HasForeignKey("PlayedGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameTracker.Class.User", "User")
                        .WithMany("playedSession")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayedGame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameTracker.Class.Game", b =>
                {
                    b.Navigation("PlaySessions");
                });

            modelBuilder.Entity("GameTracker.Class.User", b =>
                {
                    b.Navigation("playedSession");
                });
#pragma warning restore 612, 618
        }
    }
}
